// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBINqME6hiZEc9l6Ioc1uu73ZgAdVK5ROs',
    appId: '1:667852088690:web:3517c404afebd50e5ea9eb',
    messagingSenderId: '667852088690',
    projectId: 'khataconnect-7afb5',
    authDomain: 'khataconnect-7afb5.firebaseapp.com',
    storageBucket: 'khataconnect-7afb5.appspot.com',
    measurementId: 'G-0GVXH28YER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYullZ0OOP5W2Um9DjXPR_6SovKZ9FtMY',
    appId: '1:667852088690:android:1b73c4834a543b1a5ea9eb',
    messagingSenderId: '667852088690',
    projectId: 'khataconnect-7afb5',
    storageBucket: 'khataconnect-7afb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYSlvkpRkHJ6K191SZULyK1BzB9GTqii8',
    appId: '1:667852088690:ios:2ecb4d49bd865fa75ea9eb',
    messagingSenderId: '667852088690',
    projectId: 'khataconnect-7afb5',
    storageBucket: 'khataconnect-7afb5.appspot.com',
    iosBundleId: 'com.example.khataConnect',
  );
}
